### ISSUE TITLE
Easy to make RebornStorage multicrafter that is impossible to power

### ISSUE THREAD

**Issue by Mawootad** [DNSTechpack/DNS12-MC1.12.2#11]
* **Type of issue?**
  * BUG / CONFIG / CHANGE
  
* **DNS Version?**
  * 12.x.x
  

* **What should happen?** 
  * It should be extremely difficult to build a refined storage system that is physically impossible to run due to power constraints due to the RF/tick consumption being higher than the controller buffer. 
  

* **What actually happens?**
  * Unfortunately, RebornStorage multicrafter makes this really easy, as a 6x6x6 or larger crafter will consumer greater than 36k RF/tick immediately causing the controller to power down as soon as it checks if there is sufficient power to continue operating.
  
* **Description?** 
  * This issue could be prevented by increasing the buffer of the Refined Storage controller. By default it's 36k RF, which is bizarrely low. Increasing it to 2 million (the same energy buffer of a minimum tier energy cube) would make this basically a non-issue by increasing the max size to a totally absurd 22x22x22 crafter

-----

Any other info?

**Comment by robaimes** [comment]
+1 for suggesting a solution. 👍

If you know how to, make a PR for this. I'm away over the weekend so I
can't fix this until Monday at the earliest. I'll merge or do the fix when
I'm back.

Thanks!
