### ISSUE TITLE
MOD REQUEST - AE2 Stuff

### ISSUE THREAD

**Issue by Lazarix** [DNSTechpack/DNS12-MC1.12.2#12]
* **Type of issue?**
  * MOD REQUEST
  
* **DNS Version?**
  * 12.0.1
   
* **Description?** 
  * Addition of AE2 Stuff

-----

* URL: https://minecraft.curseforge.com/projects/ae2-stuff

-----

**Comment by robaimes** [comment]
Will add this after we sort out Forge issues. Basically forge update causes crashes with mods, so once all mods are updated to the new forge we will include this. 👍

**Comment by robaimes** [comment]
Added in 12.0.2.0

See #18
