### ISSUE TITLE
Mod Request - General Laymans Aesthetic Spying Screen Glass

### ISSUE THREAD

**Issue by definablefan4** [DNSTechpack/DNS12-MC1.12.2#17]
MOD REQUEST

1.12.2

https://minecraft.curseforge.com/projects/general-laymans-aesthetic-spying-screen-glass
  
General Layman's Aesthetic Spying Screen (GLASS) allows you to decorate your houses in a way not thought possible before. Ever wanted to watch the sun set whilst living in a cave? With GLASS, that is now possible!

**Comment by Madcock83** [comment]
will be looking into it
