### ISSUE TITLE
[CHANGE] to ProjectE

### ISSUE THREAD

**Issue by drakkillen** [DNSTechpack/DNS12-MC1.12.2#20]
* **DNS Version?**
  * 12.0.2.1
by changeing this line to True

"# When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file. [default: false]
    B:pregenerate=true"
it will reduce server boot time as the mod dont have to recalculate the EMC values every reboot

**Comment by robaimes** [comment]
Do you mean https://github.com/DNSTechpack/DNS12-MC1.12.2/blob/master/config/ProjectE/mapping.cfg#L38 ?

**Comment by drakkillen** [comment]
exactly
