### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by drakkillen** [DNSTechpack/DNS12-MC1.12.2#23]
* **DNS Version?**
  * 12.0.2.1
GETTING TIMED OUT WHEN TRYING TO CONNECT

  after a reboot a user had problem joining the server, console was throwing this error "tip"
"> Exception in thread "Server Watchdog" Nov 22, 2017 12:54:35 PM io.netty.util.ResourceLeakDetector reportUntracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.
" 
and here's the image of the error when logging in http://clip2net.com/s/3PGUgQA

**Comment by robaimes** [comment]
Probably stems from #19 - NO other occurrences of this
