### ISSUE TITLE
A few Pam's harvestcraft recipes not working. 

### ISSUE THREAD

**Issue by Chunkey** [DNSTechpack/DNS12-MC1.12.2#31]
* **Type of issue?**
BUG
  
* **DNS Version?**
  * DNS v12.0.3.1
  

* **What should happen?** 
Pam's recipes. So far have found that soy sauce, hot sauce, and corned beef require Pam's salt, not any:dustSalt. Soy sauce, hot sauce, and corned beef are uncraftable. Have not tested all recipes so there may be more.
  
* **What actually happens?**
 Unable to obtain items.
  

Thx^^

**Comment by Madcock83** [comment]
That may have been fixed in last update will be checking today

**Comment by Madcock83** [comment]
it has
