### ISSUE TITLE
Importer losing filterd items

### ISSUE THREAD

**Issue by Zargs** [DNSTechpack/DNS12-MC1.12.2#50]
* **Type of issue?**
  * BUG
  
* **DNS Version?**
  * 12.0.7.1
 
On my Importer from Refined Storage. Witch have 8 dusts in its filter, Works like a charm.
I put a cover from Chisel & bits on a said Importer from Refined Storage and poof. Everything in the filter is gone.
  

Any other info?

**Comment by definablefan4** [comment]
Have you tried clicking the side of the importer that is exposed?

**Comment by Zargs** [comment]
"side of teh importer" What side? What do you mean?

**Comment by definablefan4** [comment]
One side is covered by the cover, and to see the filter I assume you are clicking the cover. Have you tried clicking the actual importer?

**Comment by Zargs** [comment]
Ohh no I click on the Importer is self.
https://cdn.discordapp.com/attachments/364913370480115712/434553957520769034/2018-04-14_04.17.38.png
https://cdn.discordapp.com/attachments/364913370480115712/434554051171057664/2018-04-14_04.17.57.png
