### ISSUE TITLE
[MOD REQUEST] Project Red

### ISSUE THREAD

**Issue by lancce-Wolf** [DNSTechpack/DNS12-MC1.12.2#59]
**MOD REQUEST**
Mod Name: Project Red
What does this mod do: We all know this mod, it was in the older versions of the DNS TechPack and it got updated to the 1.12
for those wo dont know this mod: it adds a bunch of redstone stuff, new lamps, new redstone gates, redstone wires and a lot more.

Mod Links:
- [Project Red Base](https://minecraft.curseforge.com/projects/project-red-base?gameCategorySlug=mc-mods&projectID=228702)
- [Project Red Compat](https://minecraft.curseforge.com/projects/project-red-compat?gameCategorySlug=mc-mods&projectID=229050)
- [Project Red Fabrication](https://minecraft.curseforge.com/projects/project-red-fabrication?gameCategorySlug=mc-mods&projectID=230111)
- [Project Red Integration](https://minecraft.curseforge.com/projects/project-red-integration?gameCategorySlug=mc-mods&projectID=229045)
- [Project Red Lighting](https://minecraft.curseforge.com/projects/project-red-lighting?gameCategorySlug=mc-mods&projectID=229046)
- [Project Red Mechanical](https://minecraft.curseforge.com/projects/project-red-mechanical?gameCategorySlug=mc-mods&projectID=229048)
- [Project Red World](https://minecraft.curseforge.com/projects/project-red-world?gameCategorySlug=mc-mods&projectID=229049)

Dependencies:
- [CodeChicken Lib](https://minecraft.curseforge.com/projects/codechicken-lib-1-8) **This mod is already In the DNS TechPack**
- [Forge MultiPart CBE](https://minecraft.curseforge.com/projects/forge-multipart-cbe)
- [MrTJPCore](https://minecraft.curseforge.com/projects/mrtjpcore)

I have these Mods test wise on my private server.

**Comment by Madcock83** [comment]
will look
