### ISSUE TITLE
[MOD REQUEST] Wizardry

### ISSUE THREAD

**Issue by JKolkman** [DNSTechpack/DNS12-MC1.12.2#61]
**MOD REQUEST**
  
**DNS Version**
  12.x.x
 
**Description?**

Wizardry aims to be the most morbid magic mod ever. We're talking fairies that you can process into fairy jam, unicorns that want to kill you, mentally conflicted bosses, and so much more. These have not yet been implemented yet, what has been implemented is the entire spell system which is currently fully functional as well as a lot of the items and structures. 

https://minecraft.curseforge.com/projects/wizardry-mod

**Comment by JKolkman** [comment]
Basically a replacement for Ars Magica, though its still in early alpha

**Comment by Madcock83** [comment]
will look into it
