### ISSUE TITLE
lag and crash after some time

### ISSUE THREAD

**Issue by cryusion** [DNSTechpack/DNS12-MC1.12.2#63]
* **Type of issue?**
  * BUG
  
* **DNS Version?**
  * 12.1.5
  
* **What should happen?** 
no crashes and maybe minor lag
  
* **What actually happens?**
after a period of time, the game begins to lag horribly and eventually crash, this normally occurs around 2-3hrs in
  
* **Description?** 
  * Using Item X should open Y interface but, when the item is used in the hand, the client crashes.

-----

i cant really provide a actual crash log (as i couldnt find one in the packs files) but i did screenshot something that isnt right from the atlauncher console http://prntscr.com/l96ves this happens on a world that existed pre removal of galacticraft, but i havent even touched galacticraft by the time it was removed

-----

Any other info?
the modpack does not exceed my pc's ram, it used to run very well actually (albeit a couple lags here and there but not really crash or spike worthy)

**Comment by Madcock83** [comment]
what are your computer specs.   For the most part everyone has seen improvements overall

**Comment by cryusion** [comment]
8GB ram intel core i7 gtx980 graphics, the modpack has never done this before though

i did check the amount of ram usage once and it only reached about 6gb, and ive allocated a little over 7gb to ATLauncher whenever i run it and a modpack (sometimes have stuff running in the background, none of it heavy on the ram, and never caused issues before)

**Comment by Madcock83** [comment]
I have 12gb of ram, a 7700k, and a gtx1060 and i cant run version 12.0.12.0.   thats why i started working on the last update.  it runs very well for me.   All i can figure is your PC doesnt like the memory leaks that have seem to all over modded MC since around 1.2.5.  i know it sucks but a restart every hour or so for now might be the best bet. for now anyways

**Comment by cryusion** [comment]
i might try making a new world to, ive never had these memory leaks, and my pc has ran modpacks with as many as 340 mods with no issues till now... though i plan on upgrading my ram some time soon, which should help it
