### ISSUE TITLE
Incompatible WorldEdit CUI version installed in pack

### ISSUE THREAD

**Issue by Inaaca** [DNSTechpack/DNS12-MC1.12.2#74]
* **Type of issue?**
  * CONFIG
  
* **DNS Version?**
  * 12.2.beta
  

* **What should happen?** 
  * WorldEdit CUI should display selections in game
  

* **What actually happens?**
  * WorldEdit CUI does not display selections in game
  
* **Description?** 
  * The version of WorldEdit CUI included (2.2.2) requires WorldEdit 7, which is a version released for Minecraft 1.13.  
WorldEdit CUI needs to be downgraded to 2.1.2 in order to be compatible with WorldEdit 6 in the pack.

**Comment by Madcock83** [comment]
Ok. Will look into it

**Comment by Madcock83** [comment]
will be in the next version
