### ISSUE TITLE
ThermalLogistics

### ISSUE THREAD

**Issue by TheBlackedIPs** [DNSTechpack/DNS12-MC1.12.2#75]
* **Type of issue?**
  *MOD REQUEST 
  
* **DNS Version?**
  * 12.2.next version :p
  

* **Description?** 
  * 2 mods I can't live without Logistics Pipes and Iron Backpacks, Iron Backpacks been requested and labeled added on Feb 2018 a year ago although I don't see it in the back could be awaiting a non-early release?? Anyway! Logistics Pipes seems abandoned but there's ThermalLogistics updated quite recently and supposed to work like Logistics Pipes buuuut without the item-dropping Buildcraft pipes! Nice!

**Comment by Madcock83** [comment]
Pipes made it in this last update, I will look at iron backpacks next update.  All though we already have a pretty good backpacks mod.
