### ISSUE TITLE
No hostile mobs spawning

### ISSUE THREAD

**Issue by orbitraiter** [DNSTechpack/DNS12-MC1.12.2#78]
* **Type of issue?**
  * BUG / QUESTION
  
* **DNS Version?**
  * 12.2.1
  

* **What should happen?** 
Hostile mobs should spawn

  

* **What actually happens?**
No hostile mobs spawn.
  
* **Description?** 
 I've tried setting the difficulty to 3, I've checked the 
server settings, spawn-animals=true and spawn-monsters=true. I've tried /cofh killall to try to remove everything to no avail. Nothing works, if it's mobs from a mobspawner, that will work, neutral mobs do spawn. But when I go to the nether for example, no hostile mobs spawn, neither do they spawn at night, in caves, or when the light level is too low.
I checked the logs, nothing seems to be out of place, nor are there any significant errors relating to this.

-----

* Crash log: INSERT_URL_HERE
* Forge log: INSERT_URL_HERE

* Server log: INSERT_URL_HERE

-----

Any other info?
Here's the server.txt

#Minecraft server properties
#Wed Jul 17 16:02:40 PDT 2019
generator-settings=
op-permission-level=4
allow-nether=true
level-name=world
enable-query=false
allow-flight=false
prevent-proxy-connections=false
server-port=25565
max-world-size=29999984
level-type=DEFAULT
enable-rcon=false
level-seed=
force-gamemode=false
server-ip=
network-compression-threshold=256
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
snooper-enabled=true
resource-pack-sha1=
online-mode=true
resource-pack=
pvp=true
broadcast-console-to-ops=true
difficulty=3
enable-command-block=false
gamemode=0
player-idle-timeout=0
max-players=20
max-tick-time=60000
spawn-monsters=true
view-distance=10
generate-structures=true
motd=A Minecraft Server

**Comment by livnfor** [comment]
I have the same problem with no hostile mobs spawning on my server.

#Minecraft server properties
#Sun Jul 21 14:03:53 BST 2019
spawn-protection=16
max-tick-time=-1
query.port=27765
generator-settings={"landScheme"\:"vanilla","tempScheme"\:"medium_zones","rainScheme"\:"medium_zones","biomeSize"\:"medium","amplitude"\:1.0,"generateBopOre"\:true,"generatePoisonIvy"\:false,"generateBerryBushes"\:true,"generateThorns"\:false,"generateQuicksand"\:false,"generateLiquidPoison"\:true,"generateHotSprings"\:true,"generateNetherHives"\:false,"generateEndFeatures"\:true,"mainNoiseSca uleX"\:80.0,"mainNoiseSca uleY"\:160.0,"mainNoiseScaleZ"\:80.0,"coordinateScale"\:684.412,"heightScale"\:684.412,"upperLimitScale"\:512.0,"lowerLimitScale"\:512.0}
force-gamemode=false
allow-nether=true
enforce-whitelist=false
gamemode=0
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=2
spawn-monsters=true
broadcast-rcon-to-ops=true
op-permission-level=4
pvp=false
snooper-enabled=true
level-type=BIOMESOP
hardcore=false
enable-command-block=false
max-players=60
network-compression-threshold=256
max-world-size=29999984
resource-pack-sha1=
server-port=27765
rcon.port=25575
debug=false
server-ip=
spawn-npcs=true
allow-flight=true
level-name=DNSTechpack-12-2-1
view-distance=12
resource-pack=
spawn-animals=true
white-list=false
rcon.password=
generate-structures=true
max-build-height=256
online-mode=true
level-seed=
use-native-transport=true
prevent-proxy-connections=false
motd=
enable-rcon=false
defaultworldgenerator-port=

**Comment by Madcock83** [comment]
It's advanced rocketry that's doing it. I have fixed in the next update. I'm out of town at the moment and can't release it. I'll have it late tonight or tomorrow. For now either remove AR and it's lib. Or update it yourself for now
