### ISSUE TITLE
[MOD REQUEST] Ex Nihilo, bonsai Tres

### ISSUE THREAD

**Issue by SteamgoatsZora** [DNSTechpack/DNS12-MC1.12.2#79]
* **Type of issue?**
  * MOD REQUEST 
  
* **DNS Version?**
  * 12.2.3
-----

Playing on BIOSPHERE, ores scarse i think exnihilo would be a great addiotion along with  bonsai trees,, this is almost making the pack into an intresting skyblock too  (alas i spawned on the smalles island)

bonsaitrees-1.1.3-b156
exnihilocreatio-1.12.2-0.3.8.3

tested and works

**Comment by Madcock83** [comment]
This seems very specific with what your playing.  would be just another mod others would have to load even though theyre not playing with it.
